netconfig = { \
'CONFIG_FLOATTYPE_DOUBLE': '', \
'CONFIG_LEARNING_RATE': '(0.01f)', \
'CONFIG_LEARNRATE_REDUCTION': '(0.99f)', \
'CONFIG_NUM_OF_ITERATIONS': '500', \
'CONFIG_TRAININGS_PER_ITERATION': '80', \
'CONFIG_TESTS_PER_ITERATION': '8', \
'CONFIG_NUM_DATASETS_PER_FILE': '64', \
'CONFIG_DIR_TRAIN': '"train/"', \
'CONFIG_DIR_TEST': '"train/"', \
'CONFIG_NUM_TRAINFILES': '1', \
'CONFIG_NUM_TESTFILES': '1', \
'CONFIG_RANDGEN_SEED': '777', \
'CONFIG_RANDGEN_MEAN': '0.0f', \
'CONFIG_RANDGEN_RANGESIZE': '0.1f', \
'CONFIG_MATH_VECT_PARALLEL': '', \
'CONFIC_VECT_NUM_THREADS': '60', \
'CONFIG_ARRAY_ALIGNMENT': '16' \
}
