netconfig = { \
'CONFIG_FLOATTYPE_DOUBLE': '', \
'CONFIG_LEARNING_RATE': '(0.005f)', \
'CONFIG_LEARNRATE_REDUCTION': '(0.995f)', \
'REDUCE_CONV_LEARNRATE': '', \
'CONFIG_NUM_OF_ITERATIONS': '500', \
'CONFIG_TRAININGS_PER_ITERATION': '256', \
'CONFIG_TESTS_PER_ITERATION': '64', \
'CONFIG_NUM_DATASETS_PER_FILE': '1000', \
'CONFIG_DIR_TRAIN': '"train/"', \
'CONFIG_DIR_TEST': '"test/"', \
'CONFIG_NUM_TRAINFILES': '55', \
'CONFIG_NUM_TESTFILES': '10', \
'CONFIG_RANDGEN_SEED': '777', \
'CONFIG_RANDGEN_MEAN': '0.0f', \
'CONFIG_RANDGEN_RANGESIZE': '0.1f', \
'CONFIG_MATH_VECT_PARALLEL': '', \
'CONFIC_VECT_NUM_THREADS': '48', \
'CONFIG_ARRAY_ALIGNMENT': '32' \
}
