#ifndef CONFIG_H_INCLUDED
#define CONFIG_H_INCLUDED


#define CONFIG_FLOATTYPE_DOUBLE

#define CONFIG_LEARNING_RATE (0.1f)

#define CONFIG_NUM_OF_ITERATIONS 5
#define CONFIG_TRAININGS_PER_TEST 10

#define CONFIG_NUM_TRAINFILES 55
#define CONFIG_NUM_TESTFILES 10

#define CONFIG_DIR_TRAIN "train"
#define CONFIG_DIR_TEST "test"


#endif /*CONFIG_H_INCLUDED*/
